// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm">> = Specific
  const handler = {} as typeof import("../../../src/app/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dev-components/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-components">> = Specific
  const handler = {} as typeof import("../../../src/app/dev-components/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/emenu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/emenu">> = Specific
  const handler = {} as typeof import("../../../src/app/emenu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/history">> = Specific
  const handler = {} as typeof import("../../../src/app/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/menu">> = Specific
  const handler = {} as typeof import("../../../src/app/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations">> = Specific
  const handler = {} as typeof import("../../../src/app/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pos">> = Specific
  const handler = {} as typeof import("../../../src/app/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/shift/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shift">> = Specific
  const handler = {} as typeof import("../../../src/app/shift/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../../src/app/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/staff/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/schedule">> = Specific
  const handler = {} as typeof import("../../../src/app/staff/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/staff/time-tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/time-tracking">> = Specific
  const handler = {} as typeof import("../../../src/app/staff/time-tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login-pin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login-pin">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login-pin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/backups/restore/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backups/restore">> = Specific
  const handler = {} as typeof import("../../../src/app/api/backups/restore/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/backups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/backups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/checklists/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checklists/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/checklists/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/checklists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checklists">> = Specific
  const handler = {} as typeof import("../../../src/app/api/checklists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/checklists/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checklists/templates">> = Specific
  const handler = {} as typeof import("../../../src/app/api/checklists/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/crm/customers/[id]/points/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/customers/[id]/points">> = Specific
  const handler = {} as typeof import("../../../src/app/api/crm/customers/[id]/points/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/crm/customers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/customers/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/crm/customers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/crm/customers/by-qr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/customers/by-qr">> = Specific
  const handler = {} as typeof import("../../../src/app/api/crm/customers/by-qr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/crm/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/customers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/crm/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/crm/loyalty/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/loyalty">> = Specific
  const handler = {} as typeof import("../../../src/app/api/crm/loyalty/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/crm/loyalty/transaction/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/loyalty/transaction">> = Specific
  const handler = {} as typeof import("../../../src/app/api/crm/loyalty/transaction/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/discounts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discounts/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/discounts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/discounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/discounts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/discounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/giftcards/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/giftcards/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/giftcards/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/giftcards/redeem/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/giftcards/redeem">> = Specific
  const handler = {} as typeof import("../../../src/app/api/giftcards/redeem/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/giftcards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/giftcards">> = Specific
  const handler = {} as typeof import("../../../src/app/api/giftcards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/auth/otp/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/auth/otp/request">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/auth/otp/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/auth/otp/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/auth/otp/verify">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/auth/otp/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/bootstrap">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/me/loyalty/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/me/loyalty">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/me/loyalty/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/me/loyalty/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/me/loyalty/transactions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/me/loyalty/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/me/qr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/me/qr">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/me/qr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/menu/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/menu/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/menu/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/menu/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/menu">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/menu/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/merch/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/merch/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/merch/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/merch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/merch">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/merch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/orders/[id]/confirm-merch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/orders/[id]/confirm-merch">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/orders/[id]/confirm-merch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/guest/table/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest/table/resolve">> = Specific
  const handler = {} as typeof import("../../../src/app/api/guest/table/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/inventory/[id]/guest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/[id]/guest">> = Specific
  const handler = {} as typeof import("../../../src/app/api/inventory/[id]/guest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/inventory/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/inventory/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/inventory/adjust/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/adjust">> = Specific
  const handler = {} as typeof import("../../../src/app/api/inventory/adjust/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/api/inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/inventory/transfers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/transfers/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/inventory/transfers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/inventory/transfers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/transfers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/inventory/transfers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/locations/[id]/layout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations/[id]/layout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/locations/[id]/layout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/locations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/locations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/menu/categories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu/categories/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/menu/categories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/menu/categories/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu/categories/reorder">> = Specific
  const handler = {} as typeof import("../../../src/app/api/menu/categories/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/menu/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/api/menu/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/menu/items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu/items/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/menu/items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/menu/items/[id]/translations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu/items/[id]/translations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/menu/items/[id]/translations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/menu/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/menu/items">> = Specific
  const handler = {} as typeof import("../../../src/app/api/menu/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/modifiers/groups/[id]/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/modifiers/groups/[id]/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/api/modifiers/groups/[id]/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/modifiers/groups/[id]/options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/modifiers/groups/[id]/options">> = Specific
  const handler = {} as typeof import("../../../src/app/api/modifiers/groups/[id]/options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/modifiers/groups/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/modifiers/groups/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/modifiers/groups/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/modifiers/groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/modifiers/groups">> = Specific
  const handler = {} as typeof import("../../../src/app/api/modifiers/groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/modifiers/options/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/modifiers/options/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/modifiers/options/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/offline-sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/offline-sync">> = Specific
  const handler = {} as typeof import("../../../src/app/api/offline-sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/operations/kpi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operations/kpi">> = Specific
  const handler = {} as typeof import("../../../src/app/api/operations/kpi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/[id]/fiscal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/fiscal">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/[id]/fiscal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/[id]/pay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/pay">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/[id]/pay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/[id]/refund/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/refund">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/[id]/refund/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/printers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/printers/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/printers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/printers/receipt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/printers/receipt">> = Specific
  const handler = {} as typeof import("../../../src/app/api/printers/receipt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/printers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/printers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/printers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/printers/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/printers/test">> = Specific
  const handler = {} as typeof import("../../../src/app/api/printers/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/profile/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/profile/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/promotions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promotions/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/promotions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/promotions/calculate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promotions/calculate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/promotions/calculate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/promotions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promotions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/promotions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reports/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reports/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reports/financial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/financial">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reports/financial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reputation/reviews/[id]/reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reputation/reviews/[id]/reply">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reputation/reviews/[id]/reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reputation/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reputation/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reputation/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/roles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/roles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles">> = Specific
  const handler = {} as typeof import("../../../src/app/api/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/settings/board/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/board">> = Specific
  const handler = {} as typeof import("../../../src/app/api/settings/board/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/settings/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/api/settings/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/settings/pos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/pos">> = Specific
  const handler = {} as typeof import("../../../src/app/api/settings/pos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shifts/[id]/adjust/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts/[id]/adjust">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shifts/[id]/adjust/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shifts/[id]/close/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts/[id]/close">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shifts/[id]/close/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/shifts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shifts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/shifts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/[id]/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/[id]/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/[id]/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/schedule/bulk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/schedule/bulk">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/schedule/bulk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/schedule">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/time-tracking/clock-in/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/time-tracking/clock-in">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/time-tracking/clock-in/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/time-tracking/clock-out/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/time-tracking/clock-out">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/time-tracking/clock-out/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/staff/time-tracking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/time-tracking">> = Specific
  const handler = {} as typeof import("../../../src/app/api/staff/time-tracking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tables/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tables/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tables/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tasks/[id]/like/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]/like">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tasks/[id]/like/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tasks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tasks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tasks/migrate-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/migrate-status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tasks/migrate-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/taxes/calculate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/taxes/calculate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/taxes/calculate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/taxes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/taxes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/taxes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/glovo/cancellation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/glovo/cancellation">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/glovo/cancellation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/glovo/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/glovo/dispatch">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/glovo/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/ubereats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/ubereats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/ubereats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
