-- POS pravky: staff assignment, print tracking, discount type, analytics timestamps

ALTER TABLE "Table" ADD COLUMN IF NOT EXISTS "assignedStaffId" TEXT;
ALTER TABLE "Table" ADD CONSTRAINT "Table_assignedStaffId_fkey"
  FOREIGN KEY ("assignedStaffId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "discountType" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "guestCount" INTEGER;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "takenByStaffId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "servedByStaffId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "closedByStaffId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "assignedStaffId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "isPrepaid" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "invoiceEmail" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "receiptsSentTo" TEXT[] DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Order" ADD CONSTRAINT "Order_takenByStaffId_fkey"
  FOREIGN KEY ("takenByStaffId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_servedByStaffId_fkey"
  FOREIGN KEY ("servedByStaffId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_closedByStaffId_fkey"
  FOREIGN KEY ("closedByStaffId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_assignedStaffId_fkey"
  FOREIGN KEY ("assignedStaffId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "guestIndex" INTEGER;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "soldByStaffId" TEXT;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "sentToKitchen" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "sentToBar" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "served" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "acceptedAt" TIMESTAMP(3);
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "readyAt" TIMESTAMP(3);

ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_soldByStaffId_fkey"
  FOREIGN KEY ("soldByStaffId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "cashTendered" DOUBLE PRECISION;
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "changeGiven" DOUBLE PRECISION;
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "recordedByStaffId" TEXT;
